version: "3"
services:
  app_react:
    build: ./bigr-front
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  app_node:
    build: ./bigr-back
    container_name: app_node
    ports:
      - 4002:4000
    env_file:
      - ./bigr-back/.env.development
    volumes:
      - ./bigr-back:/usr/src/app
      - node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file:
      - ./bigr-back/.env.development
    ports:
      - 5433:5432
    volumes:
      - volume_db:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 4080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - app_node

volumes:
  build_react:
  volume_db:
  node_modules:
